### ISSUE TITLE
Contact for Ann Arbor site is same as for Warwick site

### ISSUE THREAD

**Issue by cmaumet** [brainhackorg/global2017#5]
Hi,

I have just noticed that the warwick email address brainhack2017-warwick@googlegroups.com also appears as a contact for the Ann Arbor site (cf. http://events.brainhack.org/global2017/locations.html#annarbor).

**Comment by carolFrohlich** [comment]
Good catch, thanks!

**Comment by cmaumet** [comment]
Thanks for the update :)
